name: Build & Publish Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
    - name: Load Google Service file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -d -i - -o app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Generate version.txt for Hub release
      run: ./gradlew generateVersionTxt
    - name: Releasing using Hub
      uses: valley-fordham/action-release-debugapk@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_CLASSIC_ONLY_REPO }}
        APP_FOLDER: app-debug
        RELEASE_TITLE: New Build