name: Build & Publish Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
    - name: Load Google Service file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
          echo $DATA
          echo $DATA | base64 -d -i 
          echo $DATA | base64 -d -i > app/google-services.json
