name: Android Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
    - name: Load Google Service file
      env:
        DATA: ${{ secrets.BANCASH_GOOGLE_SERVICES_JSON }}
      run: echo $DATA | base64 -d -i > app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run gradle tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
